---
- name: Delete AWS Resources
  hosts: all
  connection: local
  gather_facts: False
  tasks:
          - ec2_remote_facts:
                  region: us-east-1
                  filters:
                          "tag:Name=Demo"
            register: instance_list

          - set_fact:
                  instance_ids: "{{instance_list.instances|map(attribute='id')|list}}"

          - ec2:
                  region: us-east-1
                  instance_ids: "{{instance_ids}}"
                  state: absent
