---
- name: Create AWS resources
  hosts: all
  connection: local
  gather_facts: False
  vars:
          aws_region: us-east-1
  tasks:
          - ping:

          - name: Create VPC
            ec2_vpc:
                    region: "{{aws_region}}"
                    cidr_block: 10.0.0.0/16
                    internet_gateway: true
                    resource_tags:
                            Environment: Development
            register: vpc

          - name: Create subnets
            ec2_vpc_subnet:
                    region: "{{aws_region}}"
                    vpc_id: "{{vpc.vpc.id}}"
                    cidr: "10.0.0.0/24"
                    resource_tags:
                            Environment: "Development"
            register: subnets

          - name: Enable subnet Internet access
            ec2_vpc_route_table:
                    vpc_id: "{{vpc.vpc.id}}"
                    region: "{{aws_region}}"
                    tags:
                            Name: Public
                    subnets:
                            - "{{subnets.subnet.id}}"
                    routes:
                            - dest: 0.0.0.0/0
                              gateway_id: "igw"

          - name: Create security group
            ec2_group:
                    region: "{{aws_region}}"
                    name: "demo-ansible-group"
                    description: "Demo Ansible Security Group"
                    vpc_id: "{{vpc.vpc.id}}"
                    rules:
                            - proto: tcp
                              from_port: 22
                              to_port: 22
                              cidr_ip: 207.255.121.124/32
                            - proto: tcp
                              from_port: 80
                              to_port: 80
                              cidr_ip: 0.0.0.0/0
                    rules_egress:
                            - proto: all
                              cidr_ip: 0.0.0.0/0
            register: security_group

          - name: Create SSH key
            ec2_key:
                    region: "{{aws_region}}"
                    name: ansible-key
                    key_material: "{{item}}"
            with_file: ~/.ssh/id_rsa.pub
            register: ssh_key

          - name: Create instances
            ec2:
                    image: ami-66506c1c
                    region: "{{aws_region}}"
                    instance_type: t2.micro
                    instance_tags:
                            project: AnsibleAuto
                    count_tag:
                            project: AnsibleAuto
                    exact_count: 1
                    group_id: "{{security_group.group_id}}"
                    vpc_subnet_id: "{{subnets.subnet.id}}"
                    key_name: "{{ssh_key.results[0].key.name}}"
                    wait: yes
                    assign_public_ip: true
            register: instances
          - debug: msg="{{instances.tagged_instances[0].public_dns_name}}"
